services:
  - type: web
    name: telegram-support-bot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthcheck
    # Эти переменные будут доступны в контейнере
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
